import { expect, test } from 'vitest'
import { previewReview } from './preview'
import type { CachedGlyph, GlyphReview } from './types'

test('keeps an incomplete split draft inspectable instead of throwing', () => {
  const source = { syllable: '가', advanceWidth: 10, sourceGlyphHash: 'source', extraction: { fontSha256: 'font', extractionSchema: 1, pathNormalization: 1, physicalStepAlgorithm: 3 }, physicalSteps: [{ order: 0, jamo: 'ㄱ', slot: 'choseong' }, { order: 1, jamo: 'ㅏ', slot: 'jungseong' }], contours: [{ id: 0, d: 'M0 0Z', commands: [{ type: 'M', x: 0, y: 0 }, { type: 'Z' }], commandHash: 'contour', bounds: { x1: 0, y1: 0, x2: 0, y2: 0 }, commandTypes: 'MZ' }], bounds: { x1: 0, y1: 0, x2: 0, y2: 0 }, sourcePath: 'M0 0Z', hangul: { choseong: 'ㄱ', jungseong: 'ㅏ', jongseong: '', medialLayout: 'vertical', compoundMedial: null, compoundFinal: null }, signals: { contourRelation: 'deficit', commandCount: 2, oneContourMultiStep: true }, family: { queueKey: { medialLayout: 'vertical', hasFinal: false, compoundMedial: null, compoundFinal: null, physicalStepCount: 2, contourRelation: 'deficit' }, semanticKey: { choseong: 'ㄱ', jungseong: 'ㅏ', jongseong: '', medialLayout: 'vertical' } } } satisfies CachedGlyph
  const review = { reviewSchemaVersion: 2, syllable: '가', source: { extraction: source.extraction, sourceGlyphHash: 'source' }, status: 'reviewing', blockers: [], steps: [{ order: 0, jamo: 'ㄱ', geometry: [{ kind: 'split-piece', recipeId: 'draft', pieceId: 'one' }] }, { order: 1, jamo: 'ㅏ', geometry: [] }], splitRecipes: [{ splitRecipeSchemaVersion: 2, id: 'draft', sourceContourId: 0, sourceContourHash: 'contour', method: 'source-command-partition', rationale: 'draft', visualValidation: { sourceContourHash: 'contour' }, pieces: [{ id: 'one', tokens: [] }] }] } satisfies GlyphReview
  expect(previewReview(source, review).compiled.paths).toEqual([{ jamo: 'ㄱ', d: '' }, { jamo: 'ㅏ', d: '' }])
})
