import { useEffect, useMemo, useRef, useState } from 'react'
import { Link } from 'react-router'
import { Button } from '../../components/ui/Button'
import { Card } from '../../components/ui/Card'
import { PageSurface } from '../../components/ui/PageSurface'
import { retainSourceAfterSave } from './tagger-state'

type Geometry = { kind: 'contour'; contourId: number } | { kind: 'split-piece'; recipeId: string; pieceId: string }
type Review = { syllable: string; status: string; blockers: string[]; notes?: string; steps: Array<{ order: number; jamo: string; geometry: Geometry[] }>; splitRecipes: Array<{ id: string; sourceContourId: number; pieces: Array<{ id: string; ownerStep: number }> }>; approved?: unknown; [key: string]: unknown }
type Glyph = { syllable: string; advanceWidth: number; sourcePath: string; contours: Array<{ id: number; d: string }>; physicalSteps: Array<{ order: number; jamo: string }>; extraction: unknown }
type State = { source: Glyph; review: Review; compiled: { paths: Array<{ jamo: string; d: string }> }; validation: { blockers: string[] }; revision?: string }
type SaveResponse = Omit<State, 'source'> & { revision: string }
type PreviewResponse = Pick<State, 'compiled' | 'validation'>
type QueueEntry = { syllable: string; priority: number; reasons: string[]; reviewStatus?: string; blockers?: string[] }
const colors = ['#e66c58', '#4c8f8b', '#7866b8', '#bd7c2b', '#5b8c5a']
async function api<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`/__jamo-svg${path}`, init); const body = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(body.error ?? 'Tagger request failed.'); return body }
function GlyphPreview({ glyph, paths, colored, overlay }: { glyph: Glyph; paths: Array<{ d: string; jamo?: string }>; colored?: boolean; overlay?: boolean }) {
  return <svg className="h-48 w-full" viewBox={`0 0 ${glyph.advanceWidth} 2048`} role="img" aria-label={`${glyph.syllable} SVG preview`}>
    {paths.map((path, index) => <path key={`${index}-${path.d.slice(0, 16)}`} d={path.d} fill={colored ? colors[index] : '#39465b'} fillRule="evenodd" />)}
    {overlay && <path d={glyph.sourcePath} fill="none" stroke="#e66c58" strokeWidth="8" strokeDasharray="18 12" />}
  </svg>
}
export default function JamoSvgTaggerPage() {
  const [queue, setQueue] = useState<QueueEntry[]>([]); const [query, setQuery] = useState(''); const [filter, setFilter] = useState<'all' | 'needs-split'>('all'); const [index, setIndex] = useState(0)
  const [state, setState] = useState<State | null>(null); const [revision, setRevision] = useState<string>(); const [error, setError] = useState<string>(); const [overlay, setOverlay] = useState(true); const previewSequence = useRef(0)
  const filteredQueue = useMemo(() => queue.filter((item) => (filter === 'all' || item.blockers?.includes('needs-split')) && (!query || item.syllable.includes(query) || `U+${item.syllable.codePointAt(0)?.toString(16).toUpperCase()}`.includes(query.toUpperCase()))), [filter, queue, query])
  const selected = filteredQueue[index]
  useEffect(() => { void api<{ entries: QueueEntry[] }>('/queue').then(({ entries }) => setQueue(entries)).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Could not load queue.')) }, [])
  useEffect(() => { if (!selected) return; void api<State>(`/glyph?syllable=${encodeURIComponent(selected.syllable)}`).then((next) => { setState(next); setRevision(next.revision); setError(undefined) }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Could not load glyph.')) }, [selected])
  const refreshPreview = async (review: Review) => { const sequence = ++previewSequence.current; try { const result = await api<PreviewResponse>('/preview', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ review }) }); if (sequence !== previewSequence.current) return; setState((current) => current?.review === review ? { ...current, ...result } : current); setError(undefined) } catch (reason) { if (sequence === previewSequence.current) setError(reason instanceof Error ? reason.message : 'Could not refresh preview.') } }
  const assign = (contourId: number, step: number | null) => { if (!state) return; const review = { ...state.review, status: state.review.status === 'approved' || state.review.status === 'unreviewed' ? 'reviewing' : state.review.status, approved: undefined, steps: state.review.steps.map((item) => ({ ...item, geometry: item.geometry.filter((geometry) => geometry.kind !== 'contour' || geometry.contourId !== contourId).concat(item.order === step ? [{ kind: 'contour', contourId }] : []) })) }; setState({ ...state, review }); void refreshPreview(review) }
  const save = async (approve = false) => { if (!state) return; previewSequence.current += 1; try { const result = await api<SaveResponse>(approve ? '/approve' : '/save', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ review: state.review, expectedRevision: revision, reviewer: 'local-reviewer' }) }); setState((current) => current ? retainSourceAfterSave(current, result) : current); setRevision(result.revision); setQueue((items) => items.map((item) => item.syllable === result.review.syllable ? { ...item, reviewStatus: result.review.status, blockers: result.review.blockers } : item)); setError(undefined) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Save failed.') } }
  const toggleNeedsSplit = () => { if (!state) return; const review = { ...state.review, status: 'reviewing', blockers: state.review.blockers.includes('needs-split') ? state.review.blockers.filter((blocker) => blocker !== 'needs-split') : [...state.review.blockers, 'needs-split'] }; setState({ ...state, review }); void refreshPreview(review) }
  return <PageSurface contentClassName="max-w-7xl"><header className="flex items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase text-[#a85d4e]">Development only</p><h1 className="text-3xl font-bold text-[#39465b]">Jamo SVG Tagger</h1><p className="mt-2 text-sm text-[#667085]">Reviewed Pretendard 600 ownership and constrained split recipes. This does not affect the learner renderer.</p></div><Link to="/" className="text-sm font-semibold text-[#8d4c43] hover:underline">Back to learner</Link></header>
    {error && <Card className="mt-4 text-[#9d3b32]">{error}</Card>}
    <section className="mt-6 grid gap-6 lg:grid-cols-[17rem_minmax(0,1fr)]"><Card className="h-fit"><label className="text-sm font-semibold text-[#39465b]">Queue search<input className="mt-2 w-full rounded border p-2" value={query} onChange={(event) => { setQuery(event.target.value); setIndex(0) }} placeholder="syllable or U+" /></label><label className="mt-3 block text-xs font-semibold text-[#39465b]">Filter<select className="mt-1 w-full rounded border p-2" value={filter} onChange={(event) => { setFilter(event.target.value as 'all' | 'needs-split'); setIndex(0) }}><option value="all">All queue items</option><option value="needs-split">Needs split</option></select></label><p className="mt-3 text-xs text-[#667085]">{selected ? `${index + 1} / ${filteredQueue.length}` : '0'} shown · {state?.review.status ?? 'loading'}</p><div className="mt-3 space-y-1">{filteredQueue.map((item, itemIndex) => <button key={item.syllable} onClick={() => setIndex(itemIndex)} className={`w-full rounded p-2 text-left text-sm ${selected?.syllable === item.syllable ? 'bg-[#e9efff] font-bold' : 'hover:bg-[#f7f7fa]'}`}>{item.syllable} {item.blockers?.includes('needs-split') && <span className="rounded bg-[#fff0d8] px-1 text-xs text-[#9a6424]">needs split</span>}<span className="block text-xs text-[#667085]">U+{item.syllable.codePointAt(0)?.toString(16).toUpperCase()} · {item.reviewStatus ?? 'unreviewed'} · P{item.priority}</span></button>)}</div><div className="mt-4 flex gap-2"><Button variant="secondary" onClick={() => setIndex(Math.max(0, index - 1))}>Previous</Button><Button variant="secondary" onClick={() => setIndex(Math.min(Math.max(0, filteredQueue.length - 1), index + 1))}>Next</Button></div></Card>
      {state && <main className="min-w-0"><section className="grid gap-4 md:grid-cols-3"><Card><h2 className="font-bold text-[#39465b]">Source glyph</h2><GlyphPreview glyph={state.source} paths={[{ d: state.source.sourcePath }]} /></Card><Card><h2 className="font-bold text-[#39465b]">Per-jamo result</h2><GlyphPreview glyph={state.source} colored paths={state.compiled.paths} /></Card><Card><div className="flex justify-between"><h2 className="font-bold text-[#39465b]">Reconstruction</h2><label className="text-xs"><input type="checkbox" checked={overlay} onChange={(event) => setOverlay(event.target.checked)} /> Overlay source</label></div><GlyphPreview glyph={state.source} overlay={overlay} paths={state.compiled.paths} /></Card></section>
        <Card className="mt-4"><h2 className="font-bold text-[#39465b]">Contour ownership — physical order: {state.source.physicalSteps.map(({ jamo }) => jamo).join(' / ')}</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{state.source.contours.map((contour) => <article className="rounded border border-[#d8e3f2] p-3" key={contour.id}><div className="flex justify-between"><strong>Contour {contour.id + 1}</strong>{state.review.splitRecipes.some((recipe) => recipe.sourceContourId === contour.id) && <span className="text-xs text-[#9a6424]">fixed split recipe</span>}</div><GlyphPreview glyph={state.source} paths={[{ d: contour.d }]} />{state.review.splitRecipes.some((recipe) => recipe.sourceContourId === contour.id) ? <p className="text-xs text-[#667085]">Pieces: {state.review.splitRecipes.flatMap((recipe) => recipe.sourceContourId === contour.id ? recipe.pieces.map((piece) => `${piece.id} → ${state.source.physicalSteps[piece.ownerStep].jamo}`) : []).join(', ')}</p> : <select className="mt-2 w-full rounded border p-2" value={state.review.steps.find((step) => step.geometry.some((geometry) => geometry.kind === 'contour' && geometry.contourId === contour.id))?.order ?? ''} onChange={(event) => assign(contour.id, event.target.value === '' ? null : Number(event.target.value))}><option value="">Unassigned</option>{state.source.physicalSteps.map((step) => <option key={step.order} value={step.order}>{step.order + 1}. {step.jamo}</option>)}</select>}</article>)}</div></Card>
        <Card className="mt-4"><h2 className="font-bold text-[#39465b]">Validation and review</h2><p className="mt-2 text-sm">{[...new Set([...state.validation.blockers, ...state.review.blockers])].length ? `Blocked: ${[...new Set([...state.validation.blockers, ...state.review.blockers])].join(', ')}` : 'No automatic blockers. Human visual approval is still required.'}</p><label className="mt-3 block text-sm font-semibold text-[#39465b]">Review note<textarea className="mt-1 min-h-20 w-full rounded border p-2 text-sm font-normal" value={state.review.notes ?? ''} onChange={(event) => setState((current) => current && ({ ...current, review: { ...current.review, notes: event.target.value } }))} placeholder="Why this glyph needs later split work…" /></label><p className="mt-1 text-xs text-[#667085]">SVG paths use evenodd fill to preserve counters/holes.</p><div className="mt-3 flex flex-wrap gap-2"><Button variant="secondary" onClick={toggleNeedsSplit}>{state.review.blockers.includes('needs-split') ? 'Clear needs split' : 'Mark as needs split'}</Button><Button onClick={() => void save(false)}>Save review</Button><Button variant="secondary" disabled={state.validation.blockers.length > 0 || state.review.blockers.includes('needs-split')} onClick={() => void save(true)}>Approve after visual review</Button></div></Card>
      </main>}</section></PageSurface>
}
