import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router'
import { Button } from '../../components/ui/Button'
import { Card } from '../../components/ui/Card'
import { PageSurface } from '../../components/ui/PageSurface'

type Geometry = { kind: 'contour'; contourId: number } | { kind: 'split-piece'; recipeId: string; pieceId: string }
type Review = { syllable: string; status: string; blockers: string[]; steps: Array<{ order: number; jamo: string; geometry: Geometry[] }>; splitRecipes: Array<{ id: string; sourceContourId: number; pieces: Array<{ id: string; ownerStep: number }> }>; approved?: unknown; [key: string]: unknown }
type Glyph = { syllable: string; advanceWidth: number; sourcePath: string; contours: Array<{ id: number; d: string }>; physicalSteps: Array<{ order: number; jamo: string }>; extraction: unknown }
type State = { source: Glyph; review: Review; compiled: { paths: Array<{ jamo: string; d: string }> }; validation: { blockers: string[] }; revision?: string }
type QueueEntry = { syllable: string; priority: number; reasons: string[] }
const colors = ['#e66c58', '#4c8f8b', '#7866b8', '#bd7c2b', '#5b8c5a']
async function api<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`/__jamo-svg${path}`, init); const body = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(body.error ?? 'Tagger request failed.'); return body }
function GlyphPreview({ glyph, paths, colored, overlay }: { glyph: Glyph; paths: Array<{ d: string; jamo?: string }>; colored?: boolean; overlay?: boolean }) {
  return <svg className="h-48 w-full" viewBox={`0 0 ${glyph.advanceWidth} 2048`} role="img" aria-label={`${glyph.syllable} SVG preview`}>
    {paths.map((path, index) => <path key={`${index}-${path.d.slice(0, 16)}`} d={path.d} fill={colored ? colors[index] : '#39465b'} fillRule="evenodd" />)}
    {overlay && <path d={glyph.sourcePath} fill="none" stroke="#e66c58" strokeWidth="8" strokeDasharray="18 12" />}
  </svg>
}
export default function JamoSvgTaggerPage() {
  const [queue, setQueue] = useState<QueueEntry[]>([]); const [query, setQuery] = useState(''); const [index, setIndex] = useState(0)
  const [state, setState] = useState<State | null>(null); const [revision, setRevision] = useState<string>(); const [error, setError] = useState<string>(); const [overlay, setOverlay] = useState(true)
  const selected = useMemo(() => queue.filter((item) => !query || item.syllable.includes(query) || `U+${item.syllable.codePointAt(0)?.toString(16).toUpperCase()}`.includes(query.toUpperCase())), [queue, query])[index]
  useEffect(() => { void api<{ entries: QueueEntry[] }>('/queue').then(({ entries }) => setQueue(entries)).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Could not load queue.')) }, [])
  useEffect(() => { if (!selected) return; void api<State>(`/glyph?syllable=${encodeURIComponent(selected.syllable)}`).then((next) => { setState(next); setRevision(next.revision); setError(undefined) }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Could not load glyph.')) }, [selected])
  const assign = (contourId: number, step: number | null) => setState((current) => current && ({ ...current, review: { ...current.review, status: current.review.status === 'approved' || current.review.status === 'unreviewed' ? 'reviewing' : current.review.status, approved: undefined, steps: current.review.steps.map((item) => ({ ...item, geometry: item.geometry.filter((geometry) => geometry.kind !== 'contour' || geometry.contourId !== contourId).concat(item.order === step ? [{ kind: 'contour', contourId }] : []) })) } }))
  const save = async (approve = false) => { if (!state) return; try { const result = await api<State & { revision: string }>(approve ? '/approve' : '/save', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ review: state.review, expectedRevision: revision, reviewer: 'local-reviewer' }) }); setState(result); setRevision(result.revision); setError(undefined) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Save failed.') } }
  return <PageSurface contentClassName="max-w-7xl"><header className="flex items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase text-[#a85d4e]">Development only</p><h1 className="text-3xl font-bold text-[#39465b]">Jamo SVG Tagger</h1><p className="mt-2 text-sm text-[#667085]">Reviewed Pretendard 600 ownership and constrained split recipes. This does not affect the learner renderer.</p></div><Link to="/" className="text-sm font-semibold text-[#8d4c43] hover:underline">Back to learner</Link></header>
    {error && <Card className="mt-4 text-[#9d3b32]">{error}</Card>}
    <section className="mt-6 grid gap-6 lg:grid-cols-[17rem_minmax(0,1fr)]"><Card className="h-fit"><label className="text-sm font-semibold text-[#39465b]">Queue search<input className="mt-2 w-full rounded border p-2" value={query} onChange={(event) => { setQuery(event.target.value); setIndex(0) }} placeholder="syllable or U+" /></label><p className="mt-3 text-xs text-[#667085]">{selected ? `${index + 1} / ${queue.length}` : '0'} queued · {state?.review.status ?? 'loading'}</p><div className="mt-3 space-y-1">{queue.filter((item) => !query || item.syllable.includes(query) || `U+${item.syllable.codePointAt(0)?.toString(16).toUpperCase()}`.includes(query.toUpperCase())).map((item, itemIndex) => <button key={item.syllable} onClick={() => setIndex(itemIndex)} className={`w-full rounded p-2 text-left text-sm ${selected?.syllable === item.syllable ? 'bg-[#e9efff] font-bold' : 'hover:bg-[#f7f7fa]'}`}>{item.syllable} <span className="text-xs text-[#667085]">U+{item.syllable.codePointAt(0)?.toString(16).toUpperCase()} · P{item.priority}</span></button>)}</div><div className="mt-4 flex gap-2"><Button variant="secondary" onClick={() => setIndex(Math.max(0, index - 1))}>Previous</Button><Button variant="secondary" onClick={() => setIndex(Math.min(Math.max(0, queue.length - 1), index + 1))}>Next</Button></div></Card>
      {state && <main className="min-w-0"><section className="grid gap-4 md:grid-cols-3"><Card><h2 className="font-bold text-[#39465b]">Source glyph</h2><GlyphPreview glyph={state.source} paths={[{ d: state.source.sourcePath }]} /></Card><Card><h2 className="font-bold text-[#39465b]">Per-jamo result</h2><GlyphPreview glyph={state.source} colored paths={state.compiled.paths} /></Card><Card><div className="flex justify-between"><h2 className="font-bold text-[#39465b]">Reconstruction</h2><label className="text-xs"><input type="checkbox" checked={overlay} onChange={(event) => setOverlay(event.target.checked)} /> Overlay source</label></div><GlyphPreview glyph={state.source} overlay={overlay} paths={state.compiled.paths} /></Card></section>
        <Card className="mt-4"><h2 className="font-bold text-[#39465b]">Contour ownership — physical order: {state.source.physicalSteps.map(({ jamo }) => jamo).join(' / ')}</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{state.source.contours.map((contour) => <article className="rounded border border-[#d8e3f2] p-3" key={contour.id}><div className="flex justify-between"><strong>Contour {contour.id + 1}</strong>{state.review.splitRecipes.some((recipe) => recipe.sourceContourId === contour.id) && <span className="text-xs text-[#9a6424]">fixed split recipe</span>}</div><GlyphPreview glyph={state.source} paths={[{ d: contour.d }]} />{state.review.splitRecipes.some((recipe) => recipe.sourceContourId === contour.id) ? <p className="text-xs text-[#667085]">Pieces: {state.review.splitRecipes.flatMap((recipe) => recipe.sourceContourId === contour.id ? recipe.pieces.map((piece) => `${piece.id} → ${state.source.physicalSteps[piece.ownerStep].jamo}`) : []).join(', ')}</p> : <select className="mt-2 w-full rounded border p-2" value={state.review.steps.find((step) => step.geometry.some((geometry) => geometry.kind === 'contour' && geometry.contourId === contour.id))?.order ?? ''} onChange={(event) => assign(contour.id, event.target.value === '' ? null : Number(event.target.value))}><option value="">Unassigned</option>{state.source.physicalSteps.map((step) => <option key={step.order} value={step.order}>{step.order + 1}. {step.jamo}</option>)}</select>}</article>)}</div></Card>
        <Card className="mt-4"><h2 className="font-bold text-[#39465b]">Validation and review</h2><p className="mt-2 text-sm">{state.validation.blockers.length ? `Blocked: ${state.validation.blockers.join(', ')}` : 'No automatic blockers. Human visual approval is still required.'}</p><p className="mt-1 text-xs text-[#667085]">SVG paths use evenodd fill to preserve counters/holes.</p><div className="mt-3 flex gap-2"><Button onClick={() => void save(false)}>Save review</Button><Button variant="secondary" disabled={state.validation.blockers.length > 0} onClick={() => void save(true)}>Approve after visual review</Button></div></Card>
      </main>}</section></PageSurface>
}
